maximum:
  email_len: 255
  name_len: 50
image:
  size: 80
minimum:
  password: 6
gravatar:
  size: 50
paginate:
  per_page: 10
password:
  expired: 2
micro:
  content: 140
  size: 50
pic:
  size: 50
  sizemb: 5
  limit: 400
